### PR TITLE
test 4.04.2 and 4.06.0

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by hannesm** [comment]
CI failure:

```
# File "src/hostnet/hostnet_dns.ml", line 167, characters 4-31:
# Error: Unbound module Dns_forward.Rpc.Client.Make
```
~~~using vpnkit.0.1.1 and dns-forward.0.10.0~~~ (fixed in opam-repository!)

and
```
# File "cohttp/scripts/generate.ml", line 145, characters 18-19:
# Error: This expression has type string but an expression was expected of type
#          bytes
```

while compiling cohttp.0.99.0

both are unrelated IMHO

**Comment by hannesm** [comment]
another revdep failure:
```
# (cd _build/default && /home/travis/.opam/4.06.0/bin/ocamlc.opt -w -40 -g -bin-annot -I /home/travis/.opam/4.06.0/lib/bytes -I /home/travis/.opam/4.06.0/lib/cstruct -I /home/travis/.opam/4.06.0/lib/ocaml -I /home/travis/.opam/4.06.0/lib/re -I /home/travis/.opam/4.06.0/lib/result -I /home/travis/.opam/4.06.0/lib/sexplib -I /home/travis/.opam/4.06.0/lib/sexplib/0 -no-alias-deps -I lib -o lib/tar.cmo -c -impl lib/tar.pp.ml)
# File "lib/tar.ml", line 29, characters 25-31:
# Error: This expression has type string but an expression was expected of type
#          bytes
```

**Comment by yomimono** [comment]
Thanks for this (and all the other testing PRs I've merged tonight without individual thanks) and all the upstream work, @hannesm. :)

**Comment by hannesm** [comment]
@yomimono thanks for reviewing and merging :)  I still have https://github.com/mirage/mirage-device/pull/2 https://github.com/mirage/mirage-flow/pull/38 https://github.com/mirage/mirage-net-unix/pull/43 https://github.com/mirage/mirage-net/pull/11 (where the mirage-flow is actually important if we want 4.06.0 support)

**Comment by yomimono** [comment]
Merged mirage/mirage-device#2, mirage/mirage-flow#38, mirage/mirage-net-unix#43, and mirage/mirage-net#11.  Thanks for the nudges!

**Pull request merged**
