### PR TITLE
we're >=4.03, no need to open Result

### PR DESCRIPTION
**Pull request by hannesm**
sorry

### CODE REVIEW

**Comment by yomimono** [comment]
don't be sorry, it's an excuse for Travis to run its first test here :)

**Comment by samoht** [comment]
By any chance, can we keep compat with 4.02?

**Comment by hannesm** [comment]
@samoht sorry, I missed the memo to retain 4.02 support.  this particular PR (together with #2) didn't introduce the 4.03.0 constraint.  I suspect someone needs to go through a bunch of repositories and ensure 4.02 compatibility.

**Comment by hannesm** [comment]
FWIW, a `git grep 4.03` in mirage-dev/packages:
```
charrua-client/charrua-client.dev~mirage/opam:available: [ocaml-version >= "4.03"]
crunch/crunch.dev~mirage/opam:available:     [ ocaml-version >= "4.03.0" ]
datakit-ci/datakit-ci.dev~mirage/opam:available: [ocaml-version >= "4.03.0"]
functoria/functoria.dev~mirage/opam:available: [ocaml-version >= "4.03"]
imaplet-lwt/imaplet-lwt.dev~mirage/opam:available: [ ocaml-version >= "4.02.0" & ocaml-version < "4.03" ]
logs-syslog/logs-syslog.dev~mirage/opam:available: [ ocaml-version >= "4.03.0"]
mirage-block-ramdisk/mirage-block-ramdisk.dev~mirage/opam:available: [ocaml-version >= "4.03.0"]
mirage-console-solo5/mirage-console-solo5.dev~mirage/opam:available: [ocaml-version >= "4.03.0"]
mirage-console/mirage-console-unix.dev~mirage/opam:available: [ocaml-version >= "4.03.0"]
mirage-console/mirage-console-xen-cli.dev~mirage/opam:available: [ocaml-version >= "4.03.0"]
mirage-console/mirage-console-xen.dev~mirage/opam:available: [ocaml-version >= "4.03.0"]
mirage-protocols/mirage-protocols.dev~mirage/opam:available: [ ocaml-version >= "4.03.0"]
mirage-qubes/mirage-qubes.dev~mirage/opam:available: [ocaml-version >= "4.03.0"]
nbd/nbd.dev~mirage/opam:  "ppx_sexp_conv" {!= "113.33.00+4.03"}
protocol-9p/protocol-9p.dev~mirage/opam:available: [ocaml-version >= "4.03.0"]
```

**Comment by samoht** [comment]
There is no memo :-) It's just that if we can keep compat with 4.02 without too much work, I think we should try. If it is too much work, it is fine to drop it.

I've tried to add/keep support for 4.02 for some of the packages that I refactored during the previous weeks, but again, not a big deal if it is too much trouble.

**Pull request merged**
